variable "aws_region" {
  type    = string
  default = "us-east-1"
}

variable "environment" {
  type    = string
  default = "dev"
}

variable "project" {
  type    = string
  default = "cloud-network-segmentation"
}

variable "owner" {
  type    = string
  default = "eunis"
}

variable "name_prefix" {
  type    = string
  default = "cns-dev"
}

# These will be generated by automation into policy.auto.tfvars.json
variable "policy_tiers" {
  type = list(string)
}

variable "policy_rules" {
  type = list(object({
    name      = string
    from_tier = string
    to_tier   = string
    protocol  = string
    from_port = number
    to_port   = number
    desc      = string
  }))
}

variable "allow_app_https_egress" {
  description = "Allow app tier outbound HTTPS (443) to the internet for patching."
  type        = bool
  default     = true
}
